services:
  book-finder:
    build:
      context: .
      network: host
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    network_mode: host
    env_file:
      - .env.production
    environment:
      - HOSTNAME=0.0.0.0
      - NODE_OPTIONS=--dns-result-order=ipv4first --no-network-family-autoselection
    restart: unless-stopped
